# Generated by Django 6.0.1 on 2026-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailing', '0003_mailing_periodicity_and_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(
                choices=[('once', 'Один раз'), ('10min', 'Каждые 10 минут'), ('hourly', 'Каждый час'),
                         ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='once',
                max_length=10),
        ),
    ]
